### ISSUE TITLE
chat_with_retrieval not running

### ISSUE THREAD

**Issue by amscosta** [benman1/generative_ai_with_langchain#42]
Hello,
I am trying to use the scripts in the chat_with_retrieval folder .
Created a python environment with requirements. Unfortunatelly the streamlit app is crashing (please see the attached image).
I also listing the console output:

(generative_ai_with_langchain-env) c0274@c0274-i7:~/generative_ai_with_langchain/chat_with_retrieval$ streamlit run app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.23:8501

INFO:root:[Document(page_content='Madam Speaker, ...
...
metadata={'source': '/tmp/tmpa4gyz1pv/state_of_the_union.txt'})]
2024-05-13 18:23:37.354 Uncaught app exception
Traceback (most recent call last):
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/langchain/vectorstores/docarray/base.py", line 19, in _check_docarray_import
    import docarray
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/docarray/__init__.py", line 5, in <module>
    from docarray.array import DocList, DocVec
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/docarray/array/__init__.py", line 1, in <module>
    from docarray.array.any_array import AnyDocArray
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/docarray/array/any_array.py", line 22, in <module>
    from docarray.base_doc import BaseDoc
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/docarray/base_doc/__init__.py", line 1, in <module>
    from docarray.base_doc.any_doc import AnyDoc
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/docarray/base_doc/any_doc.py", line 3, in <module>
    from .doc import BaseDoc
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/docarray/base_doc/doc.py", line 22, in <module>
    from pydantic.main import ROOT_KEY
ImportError: cannot import name 'ROOT_KEY' from 'pydantic.main' (/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/pydantic/main.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/c0274/generative_ai_with_langchain/chat_with_retrieval/app.py", line 35, in <module>
    CONV_CHAIN = configure_retrieval_chain(
  File "/home/c0274/generative_ai_with_langchain/chat_with_retrieval/chat_with_documents.py", line 108, in configure_retrieval_chain
    retriever = configure_retriever(docs=docs, use_compression=use_compression)
  File "/home/c0274/generative_ai_with_langchain/chat_with_retrieval/chat_with_documents.py", line 47, in configure_retriever
    vectordb = DocArrayInMemorySearch.from_documents(splits, embeddings)
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 417, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/langchain/vectorstores/docarray/in_memory.py", line 67, in from_texts
    store = cls.from_params(embedding, **kwargs)
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/langchain/vectorstores/docarray/in_memory.py", line 38, in from_params
    _check_docarray_import()
  File "/home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/langchain/vectorstores/docarray/base.py", line 29, in _check_docarray_import
    raise ImportError(
ImportError: Could not import docarray python package. Please install it with `pip install "langchain[docarray]"`.

Any clue is very welcome.
langchain[docarray] is already installed .
![Screenshot from 2024-05-13 18-19-46](https://github.com/benman1/generative_ai_with_langchain/assets/31936244/4fc1e306-2353-42f9-9532-508a1607504d)

**Comment by benman1** [comment]
This is a very strange error. This smells of an environment problem to me. Could you please check if you have a directory`home/c0274/generative_ai_with_langchain/generative_ai_with_langchain-env/lib/python3.10/site-packages/docarray`?

**Comment by MartiMayo** [comment]
Same issue for me and I do have the directory you mention

**Comment by benman1** [comment]
This should only have been an issue of installing docarray as indicated in the error. Anyway, I've made a few changes to the environment (requirements.txt, conda yaml). Please check again with the new environment. There's also a new branch softupdate with a later version of LangChain that should work.
